# Linux/MPI Makefile for MapReduce examples, g++, MPI

CC =		mpic
CPP =		mpic++
CCFLAGS =	-g -O -I../src -DMPICH_IGNORE_CXX_SEEK
LINK =		mpic++
LINKFLAGS =	-g -O
USRLIB =	../src/libmrmpi_linux.so
SYSLIB =	-lmpich -lmpl -lpthread

include Makefile.common
